services:
  - type: web
    name: product-verification
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn product_verification.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISABLE_COLLECTSTATIC
        value: 1
    plan: standard  # This is important for ML workloads
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: /health/ 