services:
  - type: web
    name: product-verification
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn product_verification.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4 