# Generated by Django 6.0.7 on 2026-07-20 09:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verification_status', models.CharField(blank=True, max_length=30)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'), models.Index(fields=['product_code'], name='products_pr_product_e20ae7_idx'), models.Index(fields=['manufacturer'], name='products_pr_manufac_0e733c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('method', models.CharField(choices=[('image', 'Image analysis'), ('barcode', 'Barcode / QR scan'), ('combined', 'Image + barcode')], default='image', max_length=20)),
                ('status', models.CharField(choices=[('authentic', 'Authentic'), ('likely_authentic', 'Likely authentic'), ('uncertain', 'Uncertain'), ('likely_counterfeit', 'Likely counterfeit'), ('counterfeit', 'Counterfeit'), ('error', 'Could not verify')], default='error', max_length=30)),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('message', models.CharField(blank=True, max_length=500)),
                ('analysis', models.TextField(blank=True)),
                ('barcode_value', models.CharField(blank=True, max_length=64)),
                ('barcode_type', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='verifications/')),
                ('ai_model_used', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='products_ve_status_e40784_idx'), models.Index(fields=['method'], name='products_ve_method_8576c6_idx'), models.Index(fields=['created_at'], name='products_ve_created_c952fc_idx'), models.Index(fields=['verification_id'], name='products_ve_verific_0cb820_idx')],
            },
        ),
    ]
